---

django_env_vars: {
    DEBUG: True,
    DATABASE_URL: '{{ database_url }}',
    REDIS_URL: '{{ redis_url }}',
    DJANGO_SETTINGS_MODULE: {{ django_settings_module }},
    STATIC_URL: '/static/',
    SECRET_KEY: '{{ secret_key }}',
}
