
sudo: required
services:
  - docker
branches:
  only:
    - master
    - production
notifications:
  email: false
  
matrix:
  include:
    - language: python
      python:
        - "3.6"
      before_install:
        - echo "before install step"
        - bash scripts/before_install.sh

      install:
        - echo "install step"
        - bash scripts/install.sh

      script:
        - echo "script step"
        - bash scripts/script.sh

      after_success:
        - bash scripts/after_success.sh

    - language: node_js
      node_js:
        - lts/*
      before_install:
        - echo "before install step"
        - bash jupyter-lti/scripts/before_install.sh

      install:
        - echo "install step"
        - bash jupyter-lti/scripts/install.sh

      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key:
          secure: $NPM_KEY
        on:
          branch: master