sudo: required

language: python
python:
  - "3.6"

services:
  - docker

branches:
  only:
    - master
    - production

before_install:
  - echo "before install step"
  - bash scripts/before_install.sh

install:
  - echo "install step"
  - bash scripts/install.sh

script:
  - echo "script step"
  - bash scripts/script.sh

after_success:
  - bash scripts/after_success.sh