language: python
cache:
  - pip
  - apt
sudo: required
dist: trusty
addons:
  postgresql: "9.6"
python:
  - "3.6"
# whitelist
branches:
  only:
    - master
    - prod
services:
# enable docker service inside travis
  - docker
  - postgresql
  - redis-server
# before_script:
#   - bash travis/${BEFORE_SCRIPT}
# before_install:
#   - bash travis/${BEFORE_INSTALL}
#   - export PATH=$PATH:$HOME/.local/bin # put aws in the path
#   - export PYTHONPATH=`pwd`:$PYTHONPATH
#   - export DJANGO_SETTINGS_MODULE="appdj.settings.test"
#   - export REDIS_URL="redis://localhost:6379/0"
#   - export DATABASE_URL="postgres://postgres:@localhost:5432/travis_ci_test"
#   - export NVIDIA_DOCKER_HOST=http://localhost:3476
#   - export AWS_DEFAULT_REGION="us-west-2"
#   - export COVERAGE_PROCESS_START=".coveragerc"
# # command to install dependencies
# install:
#   - bash travis/${INSTALL}

# script:
#   - ls
#   - bash travis/${SCRIPT}

# after_success:
#   - bash <(curl -s https://codecov.io/bash)

# notifications:
#   slack: 3blades:RouLDGyG58awmaGkjgvh9Yuz
# matrix:
#   include:
#     - python: 3.6
#       env: SCRIPT=apitests_script.sh INSTALL=apitests_install.sh BEFORE_INSTALL=apitests_before_install.sh BEFORE_SCRIPT=apitests_before_script.sh
#     - python: 3.6
#       env: SCRIPT=unittests_script.sh INSTALL=unittests_install.sh BEFORE_INSTALL=unittests_before_install.sh BEFORE_SCRIPT=unittests_before_script.sh
jobs:
  include:
    - stage: test
      env:
        - TEST=UNIT
        - TEST=API
      before_script: bash travis/before_script.sh
      before_install: bash travis/before_install.sh
      install: bash travis/install.sh
      script: bash travis/script.sh
    - stage: deploy
      before_script: echo before script
      before_install: echo before install
      install: echo install
      script: echo "Deploying..."
env:
  global:
    - DOCKER_IMAGE_NAME="3blades/app-backend"
    - DOCKER_COMPOSE_VERSION=1.16.1