
sudo: required
services:
  - docker
branches:
  only:
    - master
    - production
notifications:
  email: false
  
matrix:
  include:
    - language: python
      python:
        - "3.6"
      before_install:
        - bash scripts/before_install.sh
      install:
        - bash scripts/install.sh
      script:
        - bash scripts/script.sh
      after_success:
        - bash scripts/after_success.sh

    - language: python
      python:
        - "3.6"
      install:
        - bash workspaces/scripts/install.sh
      script:
        - bash workspaces/scripts/script.sh
      after_success:
        - bash workspaces/scripts/after_success.sh

    - language: node_js
      node_js:
        - lts/*
      before_install:
        - bash jupyter-lti/jupyterlab/scripts/before_install.sh
      install:
        - bash jupyter-lti/jupyterlab/scripts/install.sh
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key:
          secure: $NPM_KEY
        on:
          branch: master

    - language: node_js
      node_js:
        - "10"
      install:
        - bash app-frontend/scripts/install.sh
      script:
        - bash app-frontend/scripts/script.sh             