language: python
cache:
  - pip
  - apt
sudo: required
dist: trusty
addons:
  postgresql: "9.6"
python:
  - "3.6"
# whitelist
branches:
  only:
    - setup_restful_tests
services:
# enable docker service inside travis
  - docker
  - postgresql
  - redis-server
before_script:
  - bash travis/${BEFORE_SCRIPT}
#  - sleep 10
before_install:
  - bash travis/${BEFORE_INSTALL}
# command to install dependencies
install:
  - bash travis/${INSTALL}

script:
  - ls
  - bash travis/${SCRIPT}

# after_success:
#   - bash <(curl -s https://codecov.io/bash)

# notifications:
#   slack: 3blades:RouLDGyG58awmaGkjgvh9Yuz
matrix:
  include:
    - python: 3.6
      env: SCRIPT=apitests_script.sh INSTALL=apitests_install.sh BEFORE_INSTALL=apitests_before_install.sh BEFORE_SCRIPT=apitests_before_script.sh
    - python: 3.6
      env:
        - SCRIPT=unittests_script.sh INSTALL=unittests_install.sh BEFORE_INSTALL=unittests_before_install.sh BEFORE_SCRIPT=unittests_before_script.sh
env:
  global:
    - DOCKER_IMAGE_NAME="3blades/app-backend"
    - DOCKER_COMPOSE_VERSION=1.16.1
