language: python
cache:
  - pip
  - apt
sudo: required
dist: trusty
addons:
  postgresql: "9.6"
python:
  - "3.6"
# whitelist
branches:
  only:
    - master
    - prod
services:
# enable docker service inside travis
  - docker
  - postgresql
  - redis-server
before_script:
  - echo "Before Script $TEST_SUITE"
  - bash travis/before_script.sh
before_install:
  - echo "Before Install $TEST_SUITE"
  - bash travis/before_install.sh
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - export DJANGO_SETTINGS_MODULE="appdj.settings.test"
  - export REDIS_URL="redis://localhost:6379/0"
  - export DATABASE_URL="postgres://postgres:@localhost:5432/travis_ci_test"
  - export NVIDIA_DOCKER_HOST=http://localhost:3476
  - export AWS_DEFAULT_REGION="us-west-2"
  - export COVERAGE_PROCESS_START=".coveragerc"
# command to install dependencies
install:
  - echo "Install $TEST_SUITE"
  - bash travis/install.sh

script:
  - echo "Script $TEST_SUITE"
  - bash travis/script.sh

jobs:
  include:
    - stage: deploy
      env: TEST_SUITE=none
      script: echo "Deploying..."

env:
  global:
    - DOCKER_IMAGE_NAME="3blades/app-backend"
    - DOCKER_COMPOSE_VERSION=1.16.1
  matrix:
    - TEST_SUITE=API
    - TEST_SUITE=UNIT