language: python
cache:
  - pip
  - apt
sudo: required
dist: trusty
addons:
  postgresql: "9.6"
python:
  - "3.6"
# whitelist
branches:
  only:
    - master
    - prod
services:
# enable docker service inside travis
  - docker
  - postgresql
  - redis-server

# all build steps use $TEST_SUITE env variable to run correct steps in corresponding bash script
before_script:
  - echo "Before Script $TEST_SUITE"
  - bash travis/before_script.sh

before_install:
  - echo "Before Install $TEST_SUITE"
  - bash travis/before_install.sh
  - 'if [ "$TEST_SUITE" = "UNIT" ]; then export DJANGO_SETTINGS_MODULE="appdj.settings.test"; fi'
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - export REDIS_URL="redis://localhost:6379/0"
  - export DATABASE_URL="postgres://postgres:@localhost:5432/travis_ci_test"
  - export NVIDIA_DOCKER_HOST=http://localhost:3476
  - export AWS_DEFAULT_REGION="us-west-2"
  - export COVERAGE_PROCESS_START=".coveragerc"

install:
  - echo "Install $TEST_SUITE"
  - bash travis/install.sh

script:
  - echo "Script $TEST_SUITE"
  - bash travis/script.sh

after_success:
  - echo "After Success $TEST_SUITE"
  - bash travis/after_success.sh

notifications:
  slack: 3blades:RouLDGyG58awmaGkjgvh9Yuz

# adds a jobs that will run after the tests are successful
jobs:
  include:
    - stage: deploy
      if: branch = master AND type = push
      env: TEST_SUITE=none
      script: 
        - echo "Deploying..."
        - bash config/buildDockerImage.sh

env:
  global:
    - DOCKER_IMAGE_NAME="illumidesk/app-backend"
    - DOCKER_COMPOSE_VERSION=1.16.1
# tells travis to run two builds, one for api tests and one for unit tests
  matrix:
    - TEST_SUITE=API
    - TEST_SUITE=UNIT
