version: '3'
services:
  api:
    build: .
    command: /srv/env/bin/gunicorn --bind 0.0.0.0:8080 --reload --workers 1 --log-level=DEBUG --error-logfile=- --access-logfile=- config.wsgi
    volumes:
      - .:/srv/app
      - /workspaces:/workspaces
    depends_on:
      - db
      - cache
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=8080"
      - "traefik.frontend.priority=1"
      - "traefik.frontend.rule=PathPrefix:/"
  channels:
    build: .
    command: /srv/env/bin/daphne -p 8080 -b 0.0.0.0 -v 2 config.asgi:channel_layer
    volumes:
      - .:/srv/app
      - /workspaces:/workspaces
    env_file: .env
    depends_on:
      - db
      - cache
    ports:
      - "9000:8080"
    entrypoint: ''
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sockets"
      - "traefik.port=8080"
      - "traefik.frontend.priority=2"
      - "traefik.frontend.rule=Path:/sns/{server}/,/{version}/{namespace}/projects/{project}/servers/{server}/status/"
  channel_worker:
    build: .
    command: /srv/env/bin/python manage.py runworker -v 2
    volumes:
      - .:/srv/app
      - /workspaces:/workspaces
    env_file: .env
    depends_on:
      - db
      - cache
    entrypoint: ''
  celery:
    build: .
    command: /srv/env/bin/celery -A config.celery worker -l info --without-heartbeat
    volumes:
      - .:/srv/app
      - /workspaces:/workspaces
    env_file: .env
    depends_on:
      - db
      - cache
    entrypoint: ''
  beat:
    build: .
    command: /srv/env/bin/celery -A config.celery beat -l debug
    volumes:
      - .:/srv/app
      - /workspaces:/workspaces
    depends_on:
      - db
      - cache
    env_file: .env
    entrypoint: ''
  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
  server:
    image: illumidesk/traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5001:80"
      - "8080:8080"
  nginx:
    image: illumidesk/nginx
    command: /nginx/sbin/nginx -p '' -g 'daemon off;'
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nginx"
      - "traefik.nginx.frontend.rule=PathPrefix:/media"

networks:
  default:
    external:
      name: illumidesk-net
