version: '2'
services:
  api:
    build: .
    command: /srv/env/bin/python /srv/app/manage.py runserver $PORT
    volumes:
      - .:/srv/app
      - /workspaces:/workspaces
    env_file: env
    depends_on:
      - db
      - cache
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"  
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
