version: '3'
services:
  api:
    build: .
    command: /srv/env/bin/gunicorn --bind 0.0.0.0:8080 --workers 1 --log-level=INFO --error-logfile=- --access-logfile=- config.wsgi
    env_file: .env
    volumes:
      - /workspaces:/workspaces
    environment:
      - TLS=True
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.backend=api"
      - "traefik.frontend.priority=1"
      - "traefik.frontend.rule=PathPrefix:/"
  channels:
    build: .
    command: /srv/env/bin/daphne -p 80 -b 0.0.0.0 -v 2 config.asgi:channel_layer
    env_file: .env
    ports:
      - "9000:80"
    entrypoint: ''
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sockets"
      - "traefik.frontend.priority=2"
      - "traefik.frontend.rule=Path:/sns/{server}/,/{version}/{namespace}/projects/{project}/servers/{server}/status/"
    volumes:
      - /workspaces:/workspaces
  channel_worker:
    build: .
    command: /srv/env/bin/python manage.py runworker -v 2
    env_file: .env
    entrypoint: ''
    volumes:
      - /workspaces:/workspaces
  celery:
    build: .
    command: /srv/env/bin/celery -A config.celery worker -l info --without-heartbeat
    env_file: .env
    entrypoint: ''
    volumes:
      - /workspaces:/workspaces
  beat:
    build: .
    command: /srv/env/bin/celery -A config.celery beat -l debug
    env_file: .env
    entrypoint: ''
    volumes:
      - /workspaces:/workspaces
  server:
    image: illumidesk/traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:80"
      - "8080:8080"
  nginx:
    image: illumidesk/nginx
    command: /nginx/sbin/nginx -p '' -g 'daemon off;'
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nginx"
      - "traefik.nginx.frontend.rule=PathPrefix:/media"

networks:
  default:
    external:
      name: illumidesk-net
